"""
Writes remotion/src/templates/registry.json: the one template registry the
planner (src/templates.py, src/treatments.py), the renderer
(remotion/src/templates.ts) and the editor read.

Every template is a premade animation built on a renderer component that
already exists (its `component` is an OverlayType), with the props a user
may change, the style / entrance / exit variants it offers, its default
duration and sound, and the narration cues the planner matches it on.
Run after editing the tables below:  python scripts/build_registry.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "remotion", "src", "templates", "registry.json")

ENTRANCES = ["fade", "rise", "drop", "slide-left", "slide-right", "zoom-in", "zoom-out",
             "blur", "wipe", "wipe-up", "flip", "glitch"]
EXITS = ["fade", "slide", "scale", "none"]
STYLES = ["documentary", "news", "minimal", "bold", "cinematic", "history"]
POSITIONS = ["auto", "top-left", "top", "top-right", "center", "bottom-left", "bottom", "bottom-right"]

# Shared editable props. type: string | number | enum | color | list | places | boolean
P = {
    "text": {"type": "string", "label": "Text", "max": 240},
    "subtitle": {"type": "string", "label": "Subtitle", "max": 200},
    "label": {"type": "string", "label": "Label", "max": 120},
    "value": {"type": "number", "label": "Value"},
    "suffix": {"type": "string", "label": "Unit", "max": 12},
    "items": {"type": "list", "label": "Items", "item": {"label": "string", "value": "number"}},
    "locations": {"type": "places", "label": "Places"},
    "highlight": {"type": "string", "label": "Highlight words", "max": 200},
    "body": {"type": "string", "label": "Body text", "max": 600},
    "fontScale": {"type": "number", "label": "Text size", "min": 0.6, "max": 1.8, "default": 1.0},
    "position": {"type": "enum", "label": "Position", "options": POSITIONS, "default": "auto"},
    "scale": {"type": "number", "label": "Scale", "min": 0.5, "max": 1.6, "default": 1.0},
    "opacity": {"type": "number", "label": "Opacity", "min": 0.2, "max": 1.0, "default": 1.0},
    "duration": {"type": "number", "label": "Duration (s)", "min": 1.5, "max": 15},
    "speed": {"type": "number", "label": "Animation speed", "min": 0.5, "max": 2.0, "default": 1.0},
    "theme": {"type": "enum", "label": "Colour", "options": ["accent", "gold", "red", "teal", "blue", "white", "amber"], "default": "accent"},
    "sfx": {"type": "enum", "label": "Sound", "options": ["default", "none", "impact", "whoosh", "map-whoosh", "riser", "pop", "typewriter", "paper", "page", "glitch", "glitch-transition"], "default": "default"},
    "sfxVolume": {"type": "number", "label": "Sound volume", "min": 0.0, "max": 1.0, "default": 0.3},
}
COMMON = ["position", "scale", "opacity", "duration", "speed", "theme", "sfx", "sfxVolume"]


def T(id_, name, category, component, description, *, props, duration, sfx=None,
      variant=None, theme=None, entrance="fade", exit_="fade", cues=(), styles=None,
      kind="card", emphasis="medium", tags=()):
    """One template. `kind`: card (replaces the picture), tag (rides on footage), map, transition."""
    return {
        "id": id_, "name": name, "category": category, "component": component,
        "description": description, "kind": kind, "emphasis": emphasis,
        "props": {k: P[k] for k in list(props) + COMMON if k in P},
        "defaults": {"duration": duration, "entrance": entrance, "exit": exit_,
                     **({"variant": variant} if variant else {}), **({"theme": theme} if theme else {}),
                     "sfx": sfx or {"name": "none", "volume": 0.0}},
        "variants": {"style": styles or STYLES, "entrance": ENTRANCES, "exit": EXITS},
        "cues": list(cues), "tags": list(tags),
    }


TEMPLATES = [
    # ------------------------------------------------------------- TEXT
    T("TEXT_LABEL_PILL_V1", "Label Pill", "TEXT", "stat-tag",
      "A small measurement or count riding on the footage: '930 · FEET'.",
      props=["text", "value", "suffix"], duration=4.0, entrance="rise", kind="tag", emphasis="low",
      cues=["measurement", "count"], tags=["vidrush", "label"]),
    T("TEXT_DUAL_LABELS_V1", "Dual Labels", "TEXT", "label-boxes",
      "Two boxed labels with a dotted connector for two things contrasted in one line.",
      props=["items"], duration=4.0, entrance="rise", kind="tag", cues=["contrast"]),
    T("TEXT_KICKER_V1", "Kicker", "TEXT", "kicker",
      "A short typed line in the top-left corner for a place and date said in passing.",
      props=["text"], duration=3.0, variant="top-left", entrance="slide-left", kind="tag", emphasis="low",
      sfx={"name": "typewriter", "volume": 0.25}, cues=["aside"]),
    T("TEXT_TYPEWRITER_V1", "Kinetic Title", "TEXT", "typewriter",
      "A line rising word by word in condensed display caps with a kicker and an accent rule.",
      props=["text"], duration=3.0, entrance="fade", sfx={"name": "typewriter", "volume": 0.28},
      cues=["term", "verdict"]),
    T("TEXT_QUESTION_V1", "Question", "TEXT", "typewriter",
      "The narration's question, typed and held.",
      props=["text"], duration=3.5, theme="white", entrance="fade",
      sfx={"name": "typewriter", "volume": 0.25}, cues=["question"]),
    T("TEXT_WORD_TYPE_V1", "Word Type", "TEXT", "word-type",
      "One or two words typed large in caps.",
      props=["text"], duration=2.5, variant="caps", entrance="fade", cues=["key-word"]),
    T("TEXT_SENTENCE_HIGHLIGHT_V1", "Highlight Sentence", "TEXT", "sentence-highlight",
      "The thesis of a section, words appearing left to right with the key words boxed.",
      props=["text", "highlight"], duration=4.0, entrance="fade", cues=["thesis"]),
    T("TEXT_KEY_PHRASE_V1", "Key Phrase", "TEXT", "callout",
      "Only the important phrase of the line, bold, over the footage.",
      props=["text"], duration=3.0, entrance="zoom-in", kind="tag", cues=["key-phrase"]),
    T("TEXT_WARNING_V1", "Warning Strip", "TEXT", "red-strip",
      "A red strip with caps for an alert level or a dangerous state.",
      props=["text"], duration=3.0, theme="red", entrance="wipe", sfx={"name": "impact", "volume": 0.3},
      cues=["warning", "alert"], tags=["news", "weather"]),
    T("TEXT_MEMO_V1", "Memo Box", "TEXT", "memo-box",
      "A typed memo box for a note-like line.",
      props=["text"], duration=3.5, entrance="rise", sfx={"name": "typewriter", "volume": 0.25}),
    T("TEXT_UNDERLINE_TITLE_V1", "Underline Title", "TEXT", "underline-title",
      "A title with an animated underline.",
      props=["text"], duration=3.5, entrance="fade"),
    T("TEXT_BAR_TITLE_V1", "Bar Title", "TEXT", "bar-title",
      "A title on a bar that slides in.",
      props=["text"], duration=3.5, entrance="slide-left", sfx={"name": "typewriter", "volume": 0.25}),
    T("TEXT_SWOOSH_TITLE_V1", "Swoosh Title", "TEXT", "swoosh-title",
      "A title with a hand-drawn swoosh underline.",
      props=["text"], duration=3.0, entrance="fade", sfx={"name": "whoosh", "volume": 0.3}),
    # --------------------------------------------------------- HEADLINES
    T("HEADLINE_CHAPTER_GHOST_V1", "Chapter (Ghost Word)", "HEADLINES", "chapter",
      "A chapter title with a giant translucent word drifting behind it.",
      props=["text", "subtitle"], duration=2.5, variant="echo", entrance="fade",
      sfx={"name": "impact", "volume": 0.3}, cues=["chapter"], emphasis="high"),
    T("HEADLINE_EDITORIAL_V1", "Chapter (Editorial)", "HEADLINES", "chapter",
      "A serif editorial chapter card.",
      props=["text", "subtitle"], duration=2.5, variant="editorial", entrance="fade",
      sfx={"name": "impact", "volume": 0.3}, cues=["chapter"], emphasis="high", styles=["documentary", "history", "cinematic"]),
    T("HEADLINE_TITLE_V1", "Title Card", "HEADLINES", "title",
      "The plain bold title card.",
      props=["text"], duration=3.0, entrance="zoom-in", cues=["title"], emphasis="high"),
    T("HEADLINE_BANNER_V1", "Banner", "HEADLINES", "banner",
      "A full-width banner headline.",
      props=["text", "subtitle"], duration=4.0, entrance="wipe", cues=["headline"], tags=["news"]),
    T("HEADLINE_NEWS_V1", "Breaking Headline", "HEADLINES", "lower-third",
      "A breaking-news style chyron.",
      props=["text", "subtitle"], duration=3.5, variant="chyron", theme="red", entrance="slide-left",
      cues=["breaking"], tags=["news"], kind="tag"),
    # ------------------------------------------------------ LOWER_THIRDS
    T("LT_TAG_V1", "Lower Third (Tag)", "LOWER_THIRDS", "lower-third",
      "Name and role on a small tag.", props=["text", "subtitle"], duration=3.5, variant="tag",
      entrance="slide-left", kind="tag", emphasis="low", cues=["person", "source"]),
    T("LT_LINE_V1", "Lower Third (Line)", "LOWER_THIRDS", "lower-third",
      "Name over a thin line.", props=["text", "subtitle"], duration=3.5, variant="line",
      entrance="wipe", kind="tag", emphasis="low", cues=["person", "source"]),
    T("LT_SERIF_V1", "Lower Third (Serif)", "LOWER_THIRDS", "lower-third",
      "A serif documentary lower third.", props=["text", "subtitle"], duration=3.5, variant="serif",
      entrance="fade", kind="tag", emphasis="low", styles=["documentary", "history", "cinematic"]),
    # ----------------------------------------------------------- NUMBERS
    T("NUM_BIG_COUNTER_V1", "Big Counter", "NUMBERS", "counter",
      "One large number counting up to the figure the line is about.",
      props=["value", "suffix", "text"], duration=4.5, entrance="zoom-in",
      sfx={"name": "riser", "volume": 0.25}, cues=["big-number"], emphasis="high"),
    T("NUM_PERCENT_V1", "Percentage", "NUMBERS", "stat",
      "A percentage with its animated bar and the noun it belongs to.",
      props=["value", "suffix", "text"], duration=3.5, entrance="rise",
      sfx={"name": "pop", "volume": 0.3}, cues=["percent"], emphasis="high"),
    T("NUM_NUMBER_ROLL_V1", "Number Roll", "NUMBERS", "number-roll",
      "Digits rolling into place.", props=["value", "suffix", "text"], duration=3.5, entrance="fade",
      cues=["big-number"]),
    T("NUM_TREND_V1", "Increase / Decrease", "NUMBERS", "trend",
      "A figure with an arrow for a rise or a fall: '↓ 12 FT'.",
      props=["value", "suffix", "text", "label"], duration=4.0, entrance="rise",
      sfx={"name": "pop", "volume": 0.3}, cues=["change"], emphasis="high"),
    T("NUM_RING_V1", "Ring Stat", "NUMBERS", "ring-stat",
      "A radial ring filling to a percentage, riding on the footage.",
      props=["value", "suffix", "text"], duration=4.5, entrance="zoom-in", kind="tag",
      sfx={"name": "pop", "volume": 0.3}, cues=["percent"]),
    T("NUM_DONUT_V1", "Donut", "NUMBERS", "donut",
      "A donut chart of one share.", props=["value", "suffix", "text"], duration=5.0, entrance="fade",
      cues=["percent", "share"]),
    T("NUM_PROGRESS_V1", "Progress Bar", "NUMBERS", "progress-bar",
      "A bar filling to a level against its maximum.", props=["value", "suffix", "text"], duration=4.5,
      entrance="rise", cues=["level"]),
    # ------------------------------------------------------------ CHARTS
    T("CHART_BARS_V1", "Bar Chart", "CHARTS", "bar-chart",
      "Two to five bars growing from zero, for values compared.",
      props=["text", "items"], duration=6.0, entrance="fade", cues=["compare-values"], emphasis="high"),
    T("CHART_LINE_V1", "Line Chart", "CHARTS", "line-chart",
      "A line drawing across time.", props=["text", "items"], duration=5.5, entrance="fade",
      cues=["series"]),
    T("CHART_AREA_V1", "Area Chart", "CHARTS", "area-chart",
      "A filled area across time.", props=["text", "items"], duration=6.0, entrance="fade",
      cues=["series"]),
    T("CHART_RANKING_V1", "Ranking", "CHARTS", "ranking",
      "Ranked rows revealed one by one.", props=["text", "items"], duration=5.5, entrance="fade",
      cues=["ranking"]),
    T("CHART_ICON_ARRAY_V1", "Pictogram Counter", "CHARTS", "icon-array",
      "Rows of pictograms, the counted share recoloured: 'N of M'.",
      props=["text", "value", "suffix"], duration=4.0, entrance="fade", cues=["share-of"]),
    T("CHART_SCALE_COMPARE_V1", "Scale Comparison", "CHARTS", "scale-compare",
      "Two quantities drawn to scale.", props=["text", "items"], duration=5.0, entrance="fade",
      cues=["compare-values"]),
    # ------------------------------------------------------- COMPARISONS
    T("CMP_SIDE_BY_SIDE_V1", "Comparison", "COMPARISONS", "comparison",
      "Two labelled values side by side: '2020: 40%  2026: 26%'.",
      props=["text", "items"], duration=5.0, entrance="fade", cues=["compare-values", "then-now"],
      emphasis="high"),
    T("CMP_SPLIT_V1", "Split Screen", "COMPARISONS", "split",
      "Two visuals top and bottom.", props=[], duration=4.0, entrance="wipe-up", cues=["before-after"]),
    # ---------------------------------------------------------- TIMELINES
    T("TL_LINE_V1", "Timeline", "TIMELINES", "timeline",
      "Nodes on a line drawing left to right, a label at each.",
      props=["text", "items"], duration=6.0, entrance="fade", sfx={"name": "pop", "volume": 0.35},
      cues=["sequence"], emphasis="high"),
    T("TL_RULER_V1", "Timeline (Ruler)", "TIMELINES", "timeline",
      "A ruler-style timeline.", props=["text", "items"], duration=6.0, variant="ruler", entrance="fade",
      sfx={"name": "pop", "volume": 0.35}, cues=["sequence"]),
    T("TL_YEAR_ROLL_V1", "Year Roll", "TIMELINES", "year-roll",
      "Years rolling to the one named.", props=["text", "value"], duration=5.0, entrance="fade",
      cues=["years"]),
    T("TL_SPAN_V1", "Span", "TIMELINES", "span",
      "A span between two dates.", props=["text", "items"], duration=4.5, entrance="fade",
      sfx={"name": "pop", "volume": 0.35}, cues=["span"]),
    T("TL_PATH_STEPS_V1", "Numbered Steps", "TIMELINES", "path-steps",
      "Numbered steps on a curve.", props=["text", "items"], duration=5.5, entrance="fade",
      sfx={"name": "pop", "volume": 0.35}, cues=["steps"]),
    T("TL_PROGRESS_STEPS_V1", "Progress Steps", "TIMELINES", "progress-steps",
      "Steps filling in order.", props=["text", "items"], duration=4.5, entrance="fade", cues=["steps"]),
    T("TL_DATE_STAMP_V1", "Date Stamp", "TIMELINES", "date-stamp",
      "A small date stamp in the corner.", props=["text"], duration=3.0, entrance="fade", kind="tag",
      emphasis="low", cues=["date"]),
    T("TL_DATE_TITLE_V1", "Date Card", "TIMELINES", "date-stamp",
      "A full date card: 'SEPTEMBER 23 / 2026'.", props=["text"], duration=3.0, variant="title",
      entrance="fade", sfx={"name": "impact", "volume": 0.3}, cues=["date"], emphasis="high"),
    T("TL_AGE_TAG_V1", "Age Tag", "TIMELINES", "age-tag",
      "An age or a count of years.", props=["text"], duration=3.0, variant="bottom", entrance="rise",
      kind="tag", emphasis="low", cues=["age"]),
    T("TL_CLOCK_V1", "Clock Badge", "TIMELINES", "clock-badge",
      "A time of day badge.", props=["text"], duration=3.5, entrance="fade", kind="tag", emphasis="low",
      cues=["time-of-day"]),
    # -------------------------------------------------------------- MAPS
    T("MAP_LOCATION_ZOOM_V1", "Location Zoom", "MAPS", "map",
      "Zoom from space to the place, pin and label.", props=["text", "locations"], duration=5.5,
      variant="satellite", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.3}, cues=["place"],
      kind="map", emphasis="high"),
    T("MAP_LOCATION_PULSE_V1", "Location Pulse", "MAPS", "map",
      "Zoom to the place with an alert pulse.", props=["text", "locations"], duration=5.5,
      variant="satellite-pulse", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.3},
      cues=["place", "event"], kind="map", emphasis="high", tags=["news", "weather"]),
    T("MAP_DISASTER_V1", "Disaster Map", "MAPS", "map",
      "Night-graded satellite zoom for a disaster or a weather event.", props=["text", "locations"],
      duration=5.5, variant="satellite-dark", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.3},
      cues=["place", "disaster"], kind="map", emphasis="high", tags=["weather"]),
    T("MAP_TILT_V1", "Tilted Landing", "MAPS", "map",
      "The camera tilts into a 3D angle as it lands.", props=["text", "locations"], duration=5.5,
      variant="satellite-tilt", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.3}, cues=["place"],
      kind="map"),
    T("MAP_ROUTE_SAT_V1", "Route (Satellite)", "MAPS", "map",
      "Two places, a path drawn between them over satellite imagery.", props=["text", "locations"],
      duration=6.0, variant="satellite-route", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.35},
      cues=["route"], kind="map", emphasis="high"),
    T("MAP_ROUTE_DARK_V1", "Route (Dark)", "MAPS", "map",
      "A red arc drawing between two places on a near-black map.", props=["text", "locations"],
      duration=6.0, variant="route-dark", entrance="fade", sfx={"name": "map-whoosh", "volume": 0.35},
      cues=["route"], kind="map", emphasis="high"),
    T("MAP_ROUTE_PAPER_V1", "Route (Paper)", "MAPS", "map",
      "A route on a paper map.", props=["text", "locations"], duration=6.0, variant="route-paper",
      entrance="fade", sfx={"name": "whoosh", "volume": 0.35}, cues=["route"], kind="map",
      styles=["documentary", "history"]),
    T("MAP_DISTANCE_V1", "Distance", "MAPS", "map",
      "Two places and the straight-line distance between them.", props=["text", "locations"],
      duration=6.0, variant="satellite-distance", entrance="fade", cues=["distance"], kind="map"),
    T("MAP_REGION_V1", "Region Highlight", "MAPS", "map",
      "A state or country filled and labelled.", props=["text", "locations"], duration=5.0,
      variant="region", entrance="fade", cues=["region"], kind="map", emphasis="high"),
    T("MAP_SPREAD_V1", "Multi-Location", "MAPS", "map",
      "Every named state or country lights up in turn.", props=["text", "locations"], duration=6.0,
      variant="spread", entrance="fade", cues=["several-places"], kind="map", emphasis="high"),
    T("MAP_SPREAD_DARK_V1", "Multi-Location (Dark)", "MAPS", "map",
      "The spread map on a dark base.", props=["text", "locations"], duration=6.0,
      variant="spread-dark", entrance="fade", cues=["several-places"], kind="map", tags=["news", "weather"]),
    T("MAP_INSET_V1", "Location with Inset", "MAPS", "map",
      "Zoom with a small locator map in the corner.", props=["text", "locations"], duration=5.5,
      variant="satellite-inset", entrance="fade", cues=["place"], kind="map"),
    T("MAP_MARKER_V1", "Marker", "MAPS", "map",
      "A simple pin on a vector map.", props=["text", "locations"], duration=5.0, variant="marker",
      entrance="fade", cues=["place"], kind="map", emphasis="low"),
    T("MAP_PAPER_V1", "Paper Map", "MAPS", "map",
      "A paper-look locator map.", props=["text", "locations"], duration=5.0, variant="paper",
      entrance="fade", cues=["place"], kind="map", styles=["documentary", "history"]),
    T("MAP_DARK_V1", "Dark Map", "MAPS", "map",
      "A dark vector locator map.", props=["text", "locations"], duration=5.0, variant="dark",
      entrance="fade", cues=["place"], kind="map", tags=["news"]),
    # ---------------------------------------------------------- CALLOUTS
    T("CALL_ARROW_V1", "Arrow", "CALLOUTS", "arrow",
      "An arrow pointing at something on screen with a short label.", props=["text"], duration=2.5,
      entrance="fade", kind="tag", emphasis="low", cues=["point-at"]),
    T("CALL_HIGHLIGHT_BOX_V1", "Highlight Box", "CALLOUTS", "highlight",
      "A box drawn around the thing named.", props=["text"], duration=3.0, entrance="fade", kind="tag",
      emphasis="low", cues=["this-one"]),
    T("CALL_ICON_POP_V1", "Icon Pop", "CALLOUTS", "icon-pop",
      "A pictogram that pops with its label.", props=["text", "label"], duration=3.0, entrance="zoom-in",
      kind="tag", sfx={"name": "pop", "volume": 0.3}, cues=["icon"]),
    T("CALL_BULLETS_V1", "Bullets", "CALLOUTS", "bullets",
      "Three short points revealed one by one over the footage.", props=["text", "items"], duration=5.5,
      entrance="rise", kind="tag", cues=["list"]),
    # ------------------------------------------------------------ QUOTES
    T("QUOTE_CARD_V1", "Quote Card", "QUOTES", "quote",
      "The quoted words with their speaker.", props=["text", "label"], duration=4.0, entrance="fade",
      cues=["quote"], emphasis="high"),
    # --------------------------------------------------------- DOCUMENTS
    T("DOC_ARTICLE_V1", "Article Card", "DOCUMENTS", "article-zoom",
      "A newspaper or report card with the key phrase highlighted.", props=["text", "highlight", "body"],
      duration=5.0, entrance="fade", sfx={"name": "paper", "volume": 0.35}, cues=["document", "report"],
      emphasis="high"),
    T("DOC_PAPER_V1", "Paper Record", "DOCUMENTS", "article-zoom",
      "A paper archival record.", props=["text", "highlight", "body"], duration=5.0, variant="paper",
      entrance="fade", sfx={"name": "paper", "volume": 0.35}, cues=["document", "record"],
      styles=["documentary", "history"]),
    # ------------------------------------------------------------ IMAGES
    # Photo and person cards take the scene's own image when the document
    # gives them none (Main.tsx), so the editor can drop one on any image beat.
    T("PHOTO_CARD_V1", "Framed Photo", "IMAGES", "photo-card",
      "The scene's photo on a green matte with a typed caption, VidRush's archival frame.",
      props=["text"], duration=4.5, entrance="fade", cues=["photo"], tags=["vidrush", "archival"]),
    T("PHOTO_GRID_V1", "Photo on Graph Paper", "IMAGES", "photo-card",
      "The photo pinned on graph paper with a dashed outline and a typed caption.",
      props=["text"], duration=4.5, variant="grid", entrance="fade", cues=["photo"],
      styles=["documentary", "history", "news"]),
    T("PERSON_CARD_V1", "Person Card", "IMAGES", "name-card",
      "A cutout or portrait on a coloured disc; the name types, the role fades in.",
      props=["text", "subtitle"], duration=4.5, entrance="fade", sfx={"name": "typewriter", "volume": 0.25},
      cues=["person"], emphasis="high", tags=["vidrush", "people"]),
]

# Scene-level image treatments (a still's motion, grade and effect), not overlays.
IMAGE_TREATMENTS = [
    {"id": "IMAGE_SLOW_PUSH_V1", "name": "Slow Push", "motion": "zoom-in", "treatment": "film", "effect": "ken-burns",
     "description": "A slow push into the photograph."},
    {"id": "IMAGE_PULL_OUT_V1", "name": "Pull Out", "motion": "zoom-out", "treatment": "film", "effect": "ken-burns",
     "description": "A slow pull out from the detail."},
    {"id": "IMAGE_PAN_LEFT_V1", "name": "Pan Left", "motion": "pan-left", "treatment": "film", "effect": "none",
     "description": "A slow pan across the frame."},
    {"id": "IMAGE_PAN_RIGHT_V1", "name": "Pan Right", "motion": "pan-right", "treatment": "film", "effect": "none",
     "description": "A slow pan across the frame."},
    {"id": "IMAGE_ARCHIVAL_V1", "name": "Archival", "motion": "zoom-in", "treatment": "archival", "effect": "film-flicker",
     "description": "Black-and-white grade, flicker and grain for material from the past."},
    {"id": "IMAGE_VINTAGE_V1", "name": "Vintage", "motion": "zoom-out", "treatment": "vintage", "effect": "dust",
     "description": "A warm faded grade with dust."},
    {"id": "IMAGE_LIGHT_LEAK_V1", "name": "Light Leak", "motion": "zoom-in", "treatment": "film", "effect": "light-leaks",
     "description": "A push with a warm light leak sweeping once."},
]

TRANSITIONS = [
    {"id": "TR_CUT", "name": "Clean Cut", "value": "none", "duration": 0.0, "use": "the default"},
    {"id": "TR_DISSOLVE", "name": "Cross Dissolve", "value": "fade", "duration": 0.4, "use": "a soft change of subject"},
    {"id": "TR_DIP", "name": "Dip to Black", "value": "dip", "duration": 0.5, "use": "a section ends"},
    {"id": "TR_BLUR", "name": "Blur", "value": "blur", "duration": 0.4, "use": "a change of place or time"},
    {"id": "TR_WHIP", "name": "Whip", "value": "whip", "duration": 0.35, "use": "energy, a jump between places"},
    {"id": "TR_ZOOM", "name": "Zoom", "value": "zoom", "duration": 0.4, "use": "into a detail"},
    {"id": "TR_SLIDE", "name": "Slide", "value": "slide", "duration": 0.4, "use": "the next item in a list"},
    {"id": "TR_FLASH", "name": "Light Flash", "value": "flash", "duration": 0.3, "use": "a revelation"},
    {"id": "TR_LIGHT_LEAK", "name": "Light Leak", "value": "light-leak", "duration": 0.8, "use": "into archival material"},
    {"id": "TR_FILM_BURN", "name": "Film Burn", "value": "film-burn", "duration": 0.6, "use": "a chapter opens"},
    {"id": "TR_GLITCH", "name": "Glitch", "value": "glitch", "duration": 0.3, "use": "between eras, once a video"},
    {"id": "TR_PUNCH", "name": "Punch", "value": "punch", "duration": 0.3, "use": "an impact line"},
    {"id": "TR_SPLIT_WIPE", "name": "Split Wipe", "value": "split-wipe", "duration": 0.4, "use": "a section change, doors opening on a new place"},
    {"id": "TR_BAR_WIPE", "name": "Bar Wipe", "value": "bar-wipe", "duration": 0.4, "use": "into a chapter title, once a video"},
    {"id": "TR_MOSAIC", "name": "Pixel Mosaic", "value": "mosaic", "duration": 0.5, "use": "into archival material"},
    {"id": "TR_COLOR_WASH", "name": "Colour Wash", "value": "color-wash", "duration": 0.5, "use": "into a quote"},
]

SFX = {
    "IMPACT": {"file": "impact", "volume": 0.3}, "IMPACT_SUBTLE": {"file": "impact", "volume": 0.2},
    "WHOOSH": {"file": "whoosh", "volume": 0.3}, "RISE": {"file": "riser", "volume": 0.25},
    "TEXT_HIT": {"file": "pop", "volume": 0.3}, "CLICK": {"file": "pop", "volume": 0.2},
    "TICK": {"file": "typewriter", "volume": 0.2}, "COUNTER": {"file": "typewriter", "volume": 0.22},
    "MAP_PING": {"file": "map-whoosh", "volume": 0.3}, "MAP_ROUTE": {"file": "map-whoosh", "volume": 0.35},
    "PAPER": {"file": "paper", "volume": 0.35}, "PAGE": {"file": "page", "volume": 0.3},
    "GLITCH": {"file": "glitch-transition", "volume": 0.3}, "NEWS_STING": {"file": "impact", "volume": 0.35},
    "TRANSITION": {"file": "whoosh", "volume": 0.2},
}

STYLE_PACKS = {
    "documentary": {"name": "Documentary", "theme": "gold", "fontFamily": "Inter", "chapter": "HEADLINE_EDITORIAL_V1",
                    "map": "MAP_LOCATION_ZOOM_V1", "route": "MAP_ROUTE_SAT_V1", "region": "MAP_REGION_V1",
                    "multi": "MAP_SPREAD_V1", "lowerThird": "LT_SERIF_V1", "caption": "documentary",
                    "transitions": ["fade", "light-leak", "dip", "blur", "zoom"], "animationIntensity": 0.8,
                    "sfxIntensity": 0.8, "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
    "news": {"name": "News", "theme": "red", "fontFamily": "Inter", "chapter": "HEADLINE_BANNER_V1",
             "map": "MAP_LOCATION_PULSE_V1", "route": "MAP_ROUTE_DARK_V1", "region": "MAP_REGION_V1",
             "multi": "MAP_SPREAD_DARK_V1", "lowerThird": "LT_TAG_V1", "caption": "news",
             "transitions": ["whip", "dip", "slide", "flash", "punch"], "animationIntensity": 1.0,
             "sfxIntensity": 1.0, "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
    "weather": {"name": "Weather", "theme": "amber", "fontFamily": "Inter", "chapter": "HEADLINE_CHAPTER_GHOST_V1",
                "map": "MAP_DISASTER_V1", "route": "MAP_ROUTE_DARK_V1", "region": "MAP_REGION_V1",
                "multi": "MAP_SPREAD_DARK_V1", "lowerThird": "LT_TAG_V1", "caption": "news",
                "transitions": ["dip", "whip", "blur", "flash"], "animationIntensity": 1.0,
                "sfxIntensity": 0.9, "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
    "history": {"name": "History", "theme": "gold", "fontFamily": "Inter", "chapter": "HEADLINE_EDITORIAL_V1",
                "map": "MAP_PAPER_V1", "route": "MAP_ROUTE_PAPER_V1", "region": "MAP_REGION_V1",
                "multi": "MAP_SPREAD_V1", "lowerThird": "LT_SERIF_V1", "caption": "documentary",
                "transitions": ["film-burn", "light-leak", "fade", "dip"], "animationIntensity": 0.7,
                "sfxIntensity": 0.7, "imageTreatment": "IMAGE_ARCHIVAL_V1"},
    "tech": {"name": "Tech", "theme": "teal", "fontFamily": "Inter", "chapter": "HEADLINE_TITLE_V1",
             "map": "MAP_DARK_V1", "route": "MAP_ROUTE_DARK_V1", "region": "MAP_REGION_V1",
             "multi": "MAP_SPREAD_DARK_V1", "lowerThird": "LT_LINE_V1", "caption": "modern",
             "transitions": ["blur", "zoom", "slide", "glitch"], "animationIntensity": 0.9,
             "sfxIntensity": 0.8, "imageTreatment": "IMAGE_PULL_OUT_V1"},
    "cinematic": {"name": "Cinematic", "theme": "white", "fontFamily": "Inter", "chapter": "HEADLINE_EDITORIAL_V1",
                  "map": "MAP_TILT_V1", "route": "MAP_ROUTE_SAT_V1", "region": "MAP_REGION_V1",
                  "multi": "MAP_SPREAD_V1", "lowerThird": "LT_SERIF_V1", "caption": "documentary",
                  "transitions": ["fade", "blur", "dip"], "animationIntensity": 0.6,
                  "sfxIntensity": 0.6, "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
    "minimal": {"name": "Minimal", "theme": "white", "fontFamily": "Inter", "chapter": "HEADLINE_TITLE_V1",
                "map": "MAP_LOCATION_ZOOM_V1", "route": "MAP_ROUTE_SAT_V1", "region": "MAP_REGION_V1",
                "multi": "MAP_SPREAD_V1", "lowerThird": "LT_LINE_V1", "caption": "documentary",
                "transitions": ["fade", "dip"], "animationIntensity": 0.5, "sfxIntensity": 0.5,
                "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
    "youtube_modern": {"name": "YouTube Modern", "theme": "accent", "fontFamily": "Inter",
                       "chapter": "HEADLINE_CHAPTER_GHOST_V1", "map": "MAP_LOCATION_PULSE_V1",
                       "route": "MAP_ROUTE_SAT_V1", "region": "MAP_REGION_V1", "multi": "MAP_SPREAD_V1",
                       "lowerThird": "LT_TAG_V1", "caption": "modern",
                       "transitions": ["whip", "zoom", "punch", "flash", "slide"], "animationIntensity": 1.0,
                       "sfxIntensity": 1.0, "imageTreatment": "IMAGE_SLOW_PUSH_V1"},
}

CAPTION_STYLES = {
    "documentary": {"name": "Documentary", "weight": 600, "size": 1.0, "background": "none", "emphasis": "numbers"},
    "news": {"name": "News", "weight": 700, "size": 0.95, "background": "bar", "emphasis": "keywords"},
    "modern": {"name": "Modern", "weight": 800, "size": 1.15, "background": "none", "emphasis": "keywords"},
}

MUSIC_MOODS = {
    "INTRO": 0.16, "BUILD": 0.13, "EXPLANATION": 0.10, "TENSION": 0.11, "REVELATION": 0.15,
    "EMOTIONAL": 0.12, "RESOLUTION": 0.12, "OUTRO": 0.14,
}


def main() -> None:
    reg = {
        "version": 1,
        "categories": ["TEXT", "HEADLINES", "LOWER_THIRDS", "NUMBERS", "CHARTS", "COMPARISONS", "TIMELINES",
                       "MAPS", "CALLOUTS", "QUOTES", "DOCUMENTS", "IMAGES", "TRANSITIONS", "CAPTIONS"],
        "templates": TEMPLATES,
        "imageTreatments": IMAGE_TREATMENTS,
        "transitions": TRANSITIONS,
        "sfx": SFX,
        "stylePacks": STYLE_PACKS,
        "captionStyles": CAPTION_STYLES,
        "musicMoods": MUSIC_MOODS,
        "entrances": ENTRANCES,
        "exits": EXITS,
        "positions": POSITIONS,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(reg, fh, indent=1, ensure_ascii=False)
    print(f"{len(TEMPLATES)} templates, {len(IMAGE_TREATMENTS)} image treatments, "
          f"{len(TRANSITIONS)} transitions, {len(STYLE_PACKS)} style packs -> {OUT}")


if __name__ == "__main__":
    main()
