import type React from "react";
import type { Overlay } from "../../types";
import { LOOKS as L_LibLowerThirds } from "./LibLowerThirds";
import { LOOKS as L_LibHeadlines } from "./LibHeadlines";
import { LOOKS as L_LibPhotosB } from "./LibPhotosB";
import { LOOKS as L_LibLists } from "./LibLists";
import { LOOKS as L_LibQuotes } from "./LibQuotes";
import { LOOKS as L_LibChapters } from "./LibChapters";
import { LOOKS as L_LibCallouts } from "./LibCallouts";
import { LOOKS as L_LibStatCards } from "./LibStatCards";
import { LOOKS as L_LibPhotosA } from "./LibPhotosA";
import { LOOKS as L_LibTimelines } from "./LibTimelines";
import { LOOKS as L_LibChartsB } from "./LibChartsB";
import { LOOKS as L_LibChartsA } from "./LibChartsA";
import { LOOKS as L_LibCounters } from "./LibCounters";
import { LOOKS as L_LibVectorMaps } from "./LibVectorMaps";
import { LOOKS as L_LibAtmosphere } from "./LibAtmosphere";
import { LOOKS as L_LibCinematic } from "./LibCinematic";
import { LOOKS as L_LibDigitalUI } from "./LibDigitalUI";
import { LOOKS as L_LibIcons } from "./LibIcons";
import { LOOKS as L_LibComparisons } from "./LibComparisons";
import { LOOKS as L_LibAlerts } from "./LibAlerts";
import { LOOKS as L_LibCaseFile } from "./LibCaseFile";
import { LOOKS as L_LibScience } from "./LibScience";
import { LOOKS as L_LibBasinMap } from "./LibBasinMap";
import { LOOKS as L_LibChartsC } from "./LibChartsC";
import { LOOKS as L_LibPersist } from "./LibPersist";
import { LOOKS as L_LibSpeakers } from "./LibSpeakers";
import { LOOKS as L_LibWeatherMaps } from "./LibWeatherMaps";
import { LOOKS as L_LibEditorText } from "./LibEditorText";
import { LOOKS as L_LibDateTime } from "./LibDateTime";
import { LOOKS as L_LibCountPro } from "./LibCountPro";
import { LOOKS as L_LibPhotoEditor } from "./LibPhotoEditor";
import { LOOKS as L_LibPersonFull } from "./LibPersonFull";
import { LOOKS as L_LibVideoMarks } from "./LibVideoMarks";
import { LOOKS as L_LibBoldText } from "./LibBoldText";
import { LOOKS as L_LibPackText } from "./LibPackText";
import { LOOKS as L_LibPackPlaces } from "./LibPackPlaces";
import { LOOKS as L_LibPackDates } from "./LibPackDates";
import { LOOKS as L_LibPackNumbers } from "./LibPackNumbers";
import { LOOKS as L_LibPackVR } from "./LibPackVR";
import { LOOKS as L_LibPhotosPro } from "./LibPhotosPro";
import { LOOKS as L_LibPhotosPro2 } from "./LibPhotosPro2";
import { LOOKS as L_LibDataPro } from "./LibDataPro";
import { LOOKS as L_LibMapsPro } from "./LibMapsPro";
import { LOOKS as L_LibDocsPro } from "./LibDocsPro";
import { LOOKS as L_LibNumbersPro } from "./LibNumbersPro";
import { LOOKS as L_LibTextPro } from "./LibTextPro";
import { LOOKS as L_LibGeoMaps } from "./LibGeoMaps";
import { LOOKS as L_LibSourceTag } from "./LibSourceTag";
import { LOOKS as L_LibRealData } from "./LibRealData";
import { LOOKS as L_LibPremium } from "./LibPremium";
import { LOOKS as L_LibKinetic } from "./LibKinetic";

export type Look = React.FC<{ overlay: Overlay; accent: string }>;

const pick = (from: Record<string, Look>, ids: string[]): Record<string, Look> =>
  Object.fromEntries(ids.filter((id) => from[id]).map((id) => [id, from[id]]));

/** Every library look by id (generated by lib_integrate.py from the QA-kept looks). */
export const LIBRARY: Record<string, Look> = {
  ...pick(L_LibLowerThirds, ["lt-accent-line", "lt-two-tone", "lt-glass-card", "lt-location-pin", "lt-date-place", "lt-role-badge", "lt-corner-brackets", "lt-stacked-index", "lt-slant-bar", "lt-source-credit"]),
  ...pick(L_LibHeadlines, ["hl-word-stack", "hl-split-line", "hl-wipe-bar", "hl-keyword-pop", "hl-focus-pull", "hl-letter-flip", "hl-outline-fill", "hl-marker-sweep", "hl-center-stack", "hl-ticker-slide"]),
  ...pick(L_LibPhotosB, ["pb-wipe-compare", "pb-triptych", "pb-carousel", "pb-corkboard", "pb-double-exposure", "pb-zoom-through", "pb-annotated", "pb-grid-pop", "pb-parallax-stack", "pb-date-plate"]),
  ...pick(L_LibLists, ["ls-numbered-cascade", "ls-checklist-ticks", "ls-pros-cons", "ls-top-countdown", "ls-icon-grid", "ls-process-chevrons", "ls-cycle-loop", "ls-pyramid-levels", "ls-funnel-stages", "ls-tab-reveal"]),
  ...pick(L_LibQuotes, ["qs-giant-marks", "qs-testimony-rail", "qs-side-panel", "qs-but-pivot", "qs-strike-correction", "qs-karaoke", "qs-zoom-word", "qs-said-stamp", "qs-double-cards", "qs-whisper"]),
  ...pick(L_LibChapters, ["ch-number-roll", "ch-part-divider", "ch-episode-card", "ch-letterbox", "ch-glitch-resolve", "ch-chrome-sweep", "ch-fraction-tag", "ch-coordinates", "ch-year-tape", "ch-countdown"]),
  ...pick(L_LibCallouts, ["co-circle-pulse", "co-draw-arrow", "co-bracket-label", "co-target-lock", "co-measure-line", "co-ripple-pointer", "co-speech-bubble", "co-scribble-underline", "co-spotlight", "co-chip-stack"]),
  ...pick(L_LibStatCards, ["ns-times-bigger", "ns-fraction-pie", "ns-kpi-flip-grid", "ns-before-after", "ns-change-meter", "ns-dual-gauge", "ns-podium", "ns-tug-of-war", "ns-goal-track", "ns-block-stack"]),
  ...pick(L_LibPhotosA, ["pa-polaroid-drop", "pa-tilt-card", "pa-blinds-reveal", "pa-spotlight-focus", "pa-film-strip", "pa-mosaic-assemble", "pa-torn-reveal", "pa-loupe-zoom", "pa-scan-id", "pa-ken-burns"]),
  ...pick(L_LibTimelines, ["tl-year-scroller", "tl-vertical-milestones", "tl-era-bands", "tl-calendar-flip", "tl-time-passing", "tl-decade-grid", "tl-curved-path", "tl-years-later", "tl-date-stamp-circle", "tl-then-now-years"]),
  ...pick(L_LibChartsB, ["cb-twin-lines", "cb-step-chart", "cb-range-bars", "cb-stream", "cb-donut-legend", "cb-treemap", "cb-flow-split", "cb-scatter", "cb-slope", "cb-radar"]),
  ...pick(L_LibChartsA, ["ca-bar-race", "ca-stacked-column", "ca-grouped-bars", "ca-lollipop", "ca-dot-plot", "ca-waterfall", "ca-bullet", "ca-radial-bars", "ca-heat-strip", "ca-histogram"]),
  ...pick(L_LibCounters, ["nc-speedo-gauge", "nc-led-counter", "nc-flip-clock", "nc-countdown-dial", "nc-battery", "nc-thermometer", "nc-population-clock", "nc-burst-number", "nc-segment-meter", "nc-stopwatch"]),
  ...pick(L_LibVectorMaps, ["mv-globe-spin", "mv-state-glow", "mv-arc-flight", "mv-impact-radius", "mv-choropleth-lift", "mv-pinboard-list", "mv-coordinate-hud", "mv-river-draw", "mv-country-spotlight", "mv-zoom-inset"]),
  ...pick(L_LibAtmosphere, ["fx-ink-bleed", "fx-light-streak", "fx-dust-motes", "fx-hud-scan", "fx-film-burn", "fx-shape-wipe", "fx-gradient-mesh", "fx-glitch-slice", "fx-zoom-tunnel", "fx-paper-tear"]),
  ...pick(L_LibCinematic, ["cn-place-stamp", "cn-true-events", "cn-letterbox-caption", "cn-bw-flash-intro", "cn-focus-vignette", "cn-spotlight-title", "cn-drift-quote", "cn-to-be-continued", "cn-sources-roll", "cn-chapter-progress"]),
  ...pick(L_LibDigitalUI, ["ui-social-post", "ui-comment-thread", "ui-search-bar", "ui-notification-stack", "ui-chat-bubbles", "ui-phone-screen", "ui-browser-window", "ui-video-player", "ui-email-card", "ui-poll-results"]),
  ...pick(L_LibIcons, ["ic-drop-fill", "ic-house-grid", "ic-traffic-queue", "ic-dollar-pulse", "ic-calendar-tear", "ic-hourglass", "ic-power-bolt", "ic-fire-flicker", "ic-crowd-swell", "ic-factory-smoke"]),
  ...pick(L_LibComparisons, ["cp-split-statement", "cp-balance-scale", "cp-venn", "cp-tick-table", "cp-myth-fact", "cp-spectrum-marker", "cp-quadrant-matrix", "cp-then-now-morph", "cp-mirror-bars", "cp-photo-versus"]),
  ...pick(L_LibAlerts, ["al-breaking-flag", "al-alert-toast", "al-siren-badge", "al-warning-polygon", "al-severity-meter", "al-countdown-timer", "al-live-tag", "al-emergency-stamp", "al-slim-ticker", "al-storm-track"]),
  ...pick(L_LibCaseFile, ["cf-evidence-bag", "cf-case-stamp", "cf-redacted-doc", "cf-fingerprint-scan", "cf-police-log", "cf-unknown-silhouette", "cf-evidence-markers", "cf-phone-records", "cf-cctv-frame", "cf-transcript"]),
  ...pick(L_LibScience, ["sc-water-cycle", "sc-aquifer-drop", "sc-pipe-flow", "sc-molecule-orbit", "sc-cause-chain", "sc-reservoir-levels", "sc-warming-stripes", "sc-rain-gauges", "sc-dam-level", "sc-heat-sun"]),
  ...pick(L_LibBasinMap, ["bm-usa-zoom", "bm-basin-zoom", "bm-river-network", "bm-basin-split", "bm-state-callout"]),
  ...pick(L_LibChartsC, ["cc-line-ticker", "cc-bars-ticker", "cc-columns-ticker", "cc-planned-vs-actual", "cc-two-series", "cc-snow-sites", "cc-tick-bars", "cc-tick-line", "cc-circle-row", "cc-network-tree", "cc-wave-chain"]),
  ...pick(L_LibPersist, ["ps-percent-ring", "ps-stat-ride", "ps-paper-checklist"]),
  ...pick(L_LibSpeakers, ["sp-quote-portrait", "sp-name-tag", "sp-two-voices", "sp-statement-card", "sp-checklist", "sp-circle-list", "sp-network", "sp-concept-wave", "sp-portrait-quote"]),
  ...pick(L_LibWeatherMaps, ["wx-wind-flow", "wx-rain-bands"]),
  ...pick(L_LibEditorText, ["ed-type-clean", "ed-type-terminal", "ed-word-by-word", "ed-marker-highlight", "ed-blur-in", "ed-split-reveal", "ed-box-stack", "ed-news-clipping", "ed-glass-caption", "ed-outline-fill", "ed-side-note", "ed-quote-type", "ed-question", "ed-alert-bar"]),
  ...pick(L_LibDateTime, ["dt-clean-card", "dt-calendar-page", "dt-stamp-bar", "dt-clock-time", "dt-rec-stamp", "dt-date-slam", "dt-timeline-tick", "dt-countdown-days", "dt-bold-headline", "dt-big-stack"]),
  ...pick(L_LibCountPro, ["ct-clean-count", "ct-rolling-digits", "ct-bar-percent", "ct-ring-pro", "ct-dot-grid", "ct-split-compare", "ct-corner-stat", "ct-pie-slice", "ct-money-stack"]),
  ...pick(L_LibPhotoEditor, ["pe-zoom-circle", "pe-highlight-box", "pe-focus-pull", "pe-split-panels", "pe-frame-drop", "pe-parallax", "pe-newsprint", "pe-punch-in", "pe-duotone", "pe-light-sweep", "pe-polaroid-pan", "pe-case-file", "pe-circle-spotlight", "pe-magnify", "pe-red-arrow"]),
  ...pick(L_LibPersonFull, ["pf-profile", "pf-dossier", "pf-split-name", "pf-spotlight", "pf-magazine"]),
  ...pick(L_LibVideoMarks, ["vm-arrow", "vm-circle", "vm-box"]),
  // Text only, the sound built in (LookSounds): the letter-drop date and the bold count.
  ...pick(L_LibBoldText, ["dt-letter-drop", "bt-count"]),
  // Pack D, text emphasis and news lines (LibPackText): clean Anton words, the sound built in.
  ...pick(L_LibPackText, ["txt-key-phrase", "txt-quote-line", "txt-headline-words", "txt-breaking-tag", "txt-question",
    "txt-bullet-trio", "txt-what-we-know", "txt-mini-timeline", "txt-before-after", "txt-underline-sweep",
    "txt-kicker-headline", "txt-chapter-minimal"]),
  // Pack C, places and labels (LibPackPlaces): where it is, what it is, who shot it; the sound in look_sounds.json.
  ...pick(L_LibPackPlaces, ["plc-location-tag", "plc-region-label", "plc-section-marker", "plc-route-label",
    "plc-river-gauge", "plc-distance-line", "plc-coordinates", "plc-source-credit", "plc-footage-tag",
    "plc-warning-label", "plc-place-time", "plc-where-lower"]),
  // Pack A, dates and times (LibPackDates): clean Anton dates at their places; the sound in look_sounds.json.
  ...pick(L_LibPackDates, ["dtx-time-stamp", "dtx-date-top", "dtx-date-place", "dtx-date-range", "dtx-day-marker",
    "dtx-time-of-day", "dtx-lead-time", "dtx-updated-stamp", "dtx-week-strip", "dtx-weekday-stack", "dtx-year-marker",
    "dtx-relative-tag", "dtx-clock-live"]),
  // Pack B, numbers and stats (LibPackNumbers): odometer figures, a soft tick per digit and a click on the landing.
  ...pick(L_LibPackNumbers, ["num-lower-third", "num-percent-line", "num-rainfall", "num-wind-gauge", "num-big-figure",
    "num-versus", "num-trend-arrow", "num-rank", "num-split-stat", "num-water-level", "num-temperature", "num-money",
    "num-step-of"]),
  // Pack VR, VidRush's date / time / caption text (LibPackVR): one place per look, the sound scheduled on its frames.
  ...pick(L_LibPackVR, ["vr-date-hero", "vr-time-card", "vr-caption-typed", "vr-year-line"]),
  // Photo looks, pro set (LibPhotosPro / LibPhotosPro2): full-frame photo moments, the sound in the registry;
  // switched on 2026-10-02 (the owner approved the contact sheet).
  ...pick(L_LibPhotosPro, ["px-aperture-iris", "px-slit-reveal", "px-color-bloom", "px-diagonal-slices", "px-level-line",
    "px-detail-inset", "px-viewfinder", "px-torn-strips", "px-folded-print", "px-field-journal", "px-magazine-spread",
    "px-postcard"]),
  ...pick(L_LibPhotosPro2, ["px-contact-sheet", "px-negative-flip", "px-darkroom", "px-slide-projector", "px-flatbed-scan",
    "px-shutter-burst", "px-album-page", "px-archive-stamp", "px-book-plate", "px-archive-envelope", "px-drying-line",
    "px-dated-cascade", "px-then-now"]),
  // Pro data (LibDataPro): charts, figures and a reservoir section that draw like a documentary's graphics desk.
  // Registered with autoPick false: in the editor only, until the owner switches them on.
  ...pick(L_LibDataPro, ["dx-line-endpoint", "dx-ghost-bars", "dx-nested-squares", "dx-unit-split", "dx-filled-figure",
    "dx-capacity-gauge", "dx-drum-counter", "dx-reservoir-section"]),
  // Pro maps (LibMapsPro): graded real imagery and vector outlines in one projection, refined markers and labels.
  ...pick(L_LibMapsPro, ["mx-globe-dive", "mx-terrain-pin", "mx-route-draw", "mx-measure-line", "mx-region-pulse",
    "mx-path-trace", "mx-pull-back"]),
  // Auto maps (LibGeoMaps): a named river, canal, lake, reservoir or dam on real geography (src/automaps.py).
  // Registered autoPick false: only the planner path behind config.AUTO_MAPS places them.
  ...pick(L_LibGeoMaps, ["geo-river-trace", "geo-reservoir"]),
  // The source tag (LibSourceTag): "SOURCE: USBR, 2024" in a low corner, for a fact whose source the narration
  // names (src/sources.py). Registered autoPick false: only the planner path behind config.SOURCE_TAGS places it.
  ...pick(L_LibSourceTag, ["src-tag"]),
  // Real data graphics (LibRealData): charts of the official numbers (USBR, USGS, the Drought Monitor, NOAA) behind
  // a narration's water and weather facts, the source and the date of the data in the corner (src/datagraphics.py).
  // Registered autoPick false: only the planner path behind config.DATA_GRAPHICS places them.
  ...pick(L_LibRealData, ["rd-line", "rd-number", "rd-bars", "rd-gauge"]),
  // Pro documents and kinetic text (LibDocsPro): real type on real-looking paper, a camera that finds the line.
  ...pick(L_LibDocsPro, ["kx-article-zoom", "kx-official-memo", "kx-report-cover", "kx-handwritten-note", "kx-keyword-stack",
    "kx-quote-portrait", "kx-alert-strip", "kx-definition", "kx-letter-signature", "kx-social-post"]),
  // Numbers pro (LibNumbersPro): figures in digits with their unit as said, a soft tick on the landing;
  // "autoPick": false until the owner approves them from their contact sheets.
  ...pick(L_LibNumbersPro, ["nx-stat-context", "nx-frame-share", "nx-ring-label", "nx-delta-arrow", "nx-money-roll",
    "nx-dimension", "nx-callout-box", "nx-callout-pair", "nx-number-line", "nx-record-floor", "nx-rate-fraction",
    "nx-rank-rows", "nx-inline-count"]),
  // Text pro (LibTextPro): the narration's own words, one device and one place each, no bar under a long line;
  // "autoPick": false until the owner approves them.
  ...pick(L_LibTextPro, ["tx-sentence-highlight", "tx-typewriter-lower", "tx-kicker-headline", "tx-word-kinetic",
    "tx-quote-serif", "tx-pull-quote", "tx-statement-card", "tx-name-card", "tx-question", "tx-contrast", "tx-ink-reveal",
    "tx-notice"]),
  // Premium (LibPremium, 2026-10-05): a document spotlight with a drawn loop and callout, a photo focus with a ring,
  // a chart that draws in, a map path between two places, a number reveal; the planner picks them where the line asks.
  ...pick(L_LibPremium, ["pr-doc-spotlight", "pr-photo-focus", "pr-graph-build", "pr-map-path", "pr-number-reveal"]),
  // Kinetic type (LibKinetic, 2026-10-05): the words, figures, shares, multipliers, dates and names the narration says,
  // in one editorial type system with three directions (typeKit.tsx) - the replacement of the outlined condensed words.
  ...pick(L_LibKinetic, ["kt-keyword", "kt-number", "kt-chip", "kt-percent", "kt-progress", "kt-multiplier", "kt-compare",
    "kt-date", "kt-year", "kt-time", "kt-lower-third", "kt-statement"]),
};
