import type React from "react";
import type { Overlay } from "../../types";
import { LOOKS as L_LibLowerThirds } from "./LibLowerThirds";
import { LOOKS as L_LibHeadlines } from "./LibHeadlines";
import { LOOKS as L_LibPhotosB } from "./LibPhotosB";
import { LOOKS as L_LibLists } from "./LibLists";
import { LOOKS as L_LibQuotes } from "./LibQuotes";
import { LOOKS as L_LibChapters } from "./LibChapters";
import { LOOKS as L_LibCallouts } from "./LibCallouts";
import { LOOKS as L_LibStatCards } from "./LibStatCards";
import { LOOKS as L_LibPhotosA } from "./LibPhotosA";
import { LOOKS as L_LibTimelines } from "./LibTimelines";
import { LOOKS as L_LibChartsB } from "./LibChartsB";
import { LOOKS as L_LibChartsA } from "./LibChartsA";
import { LOOKS as L_LibCounters } from "./LibCounters";
import { LOOKS as L_LibVectorMaps } from "./LibVectorMaps";
import { LOOKS as L_LibAtmosphere } from "./LibAtmosphere";
import { LOOKS as L_LibCinematic } from "./LibCinematic";
import { LOOKS as L_LibDigitalUI } from "./LibDigitalUI";
import { LOOKS as L_LibIcons } from "./LibIcons";
import { LOOKS as L_LibComparisons } from "./LibComparisons";
import { LOOKS as L_LibAlerts } from "./LibAlerts";
import { LOOKS as L_LibCaseFile } from "./LibCaseFile";
import { LOOKS as L_LibScience } from "./LibScience";

export type Look = React.FC<{ overlay: Overlay; accent: string }>;

const pick = (from: Record<string, Look>, ids: string[]): Record<string, Look> =>
  Object.fromEntries(ids.filter((id) => from[id]).map((id) => [id, from[id]]));

/** Every library look by id (generated by lib_integrate.py from the QA-kept looks). */
export const LIBRARY: Record<string, Look> = {
  ...pick(L_LibLowerThirds, ["lt-accent-line", "lt-two-tone", "lt-glass-card", "lt-location-pin", "lt-date-place", "lt-role-badge", "lt-corner-brackets", "lt-stacked-index", "lt-slant-bar", "lt-source-credit"]),
  ...pick(L_LibHeadlines, ["hl-word-stack", "hl-split-line", "hl-wipe-bar", "hl-keyword-pop", "hl-focus-pull", "hl-letter-flip", "hl-outline-fill", "hl-marker-sweep", "hl-center-stack", "hl-ticker-slide"]),
  ...pick(L_LibPhotosB, ["pb-wipe-compare", "pb-triptych", "pb-carousel", "pb-corkboard", "pb-double-exposure", "pb-zoom-through", "pb-annotated", "pb-grid-pop", "pb-parallax-stack", "pb-date-plate"]),
  ...pick(L_LibLists, ["ls-numbered-cascade", "ls-checklist-ticks", "ls-pros-cons", "ls-top-countdown", "ls-icon-grid", "ls-process-chevrons", "ls-cycle-loop", "ls-pyramid-levels", "ls-funnel-stages", "ls-tab-reveal"]),
  ...pick(L_LibQuotes, ["qs-giant-marks", "qs-testimony-rail", "qs-side-panel", "qs-but-pivot", "qs-strike-correction", "qs-karaoke", "qs-zoom-word", "qs-said-stamp", "qs-double-cards", "qs-whisper"]),
  ...pick(L_LibChapters, ["ch-number-roll", "ch-part-divider", "ch-episode-card", "ch-letterbox", "ch-glitch-resolve", "ch-chrome-sweep", "ch-fraction-tag", "ch-coordinates", "ch-year-tape", "ch-countdown"]),
  ...pick(L_LibCallouts, ["co-circle-pulse", "co-draw-arrow", "co-bracket-label", "co-target-lock", "co-measure-line", "co-ripple-pointer", "co-speech-bubble", "co-scribble-underline", "co-spotlight", "co-chip-stack"]),
  ...pick(L_LibStatCards, ["ns-times-bigger", "ns-fraction-pie", "ns-kpi-flip-grid", "ns-before-after", "ns-change-meter", "ns-dual-gauge", "ns-podium", "ns-tug-of-war", "ns-goal-track", "ns-block-stack"]),
  ...pick(L_LibPhotosA, ["pa-polaroid-drop", "pa-tilt-card", "pa-blinds-reveal", "pa-spotlight-focus", "pa-film-strip", "pa-mosaic-assemble", "pa-torn-reveal", "pa-loupe-zoom", "pa-scan-id", "pa-ken-burns"]),
  ...pick(L_LibTimelines, ["tl-year-scroller", "tl-vertical-milestones", "tl-era-bands", "tl-calendar-flip", "tl-time-passing", "tl-decade-grid", "tl-curved-path", "tl-years-later", "tl-date-stamp-circle", "tl-then-now-years"]),
  ...pick(L_LibChartsB, ["cb-twin-lines", "cb-step-chart", "cb-range-bars", "cb-stream", "cb-donut-legend", "cb-treemap", "cb-flow-split", "cb-scatter", "cb-slope", "cb-radar"]),
  ...pick(L_LibChartsA, ["ca-bar-race", "ca-stacked-column", "ca-grouped-bars", "ca-lollipop", "ca-dot-plot", "ca-waterfall", "ca-bullet", "ca-radial-bars", "ca-heat-strip", "ca-histogram"]),
  ...pick(L_LibCounters, ["nc-speedo-gauge", "nc-led-counter", "nc-flip-clock", "nc-countdown-dial", "nc-battery", "nc-thermometer", "nc-population-clock", "nc-burst-number", "nc-segment-meter", "nc-stopwatch"]),
  ...pick(L_LibVectorMaps, ["mv-globe-spin", "mv-state-glow", "mv-arc-flight", "mv-impact-radius", "mv-choropleth-lift", "mv-pinboard-list", "mv-coordinate-hud", "mv-river-draw", "mv-country-spotlight", "mv-zoom-inset"]),
  ...pick(L_LibAtmosphere, ["fx-ink-bleed", "fx-light-streak", "fx-dust-motes", "fx-hud-scan", "fx-film-burn", "fx-shape-wipe", "fx-gradient-mesh", "fx-glitch-slice", "fx-zoom-tunnel", "fx-paper-tear"]),
  ...pick(L_LibCinematic, ["cn-place-stamp", "cn-true-events", "cn-letterbox-caption", "cn-bw-flash-intro", "cn-focus-vignette", "cn-spotlight-title", "cn-drift-quote", "cn-to-be-continued", "cn-sources-roll", "cn-chapter-progress"]),
  ...pick(L_LibDigitalUI, ["ui-social-post", "ui-comment-thread", "ui-search-bar", "ui-notification-stack", "ui-chat-bubbles", "ui-phone-screen", "ui-browser-window", "ui-video-player", "ui-email-card", "ui-poll-results"]),
  ...pick(L_LibIcons, ["ic-drop-fill", "ic-house-grid", "ic-traffic-queue", "ic-dollar-pulse", "ic-calendar-tear", "ic-hourglass", "ic-power-bolt", "ic-fire-flicker", "ic-crowd-swell", "ic-factory-smoke"]),
  ...pick(L_LibComparisons, ["cp-split-statement", "cp-balance-scale", "cp-venn", "cp-tick-table", "cp-myth-fact", "cp-spectrum-marker", "cp-quadrant-matrix", "cp-then-now-morph", "cp-mirror-bars", "cp-photo-versus"]),
  ...pick(L_LibAlerts, ["al-breaking-flag", "al-alert-toast", "al-siren-badge", "al-warning-polygon", "al-severity-meter", "al-countdown-timer", "al-live-tag", "al-emergency-stamp", "al-slim-ticker", "al-storm-track"]),
  ...pick(L_LibCaseFile, ["cf-evidence-bag", "cf-case-stamp", "cf-redacted-doc", "cf-fingerprint-scan", "cf-police-log", "cf-unknown-silhouette", "cf-evidence-markers", "cf-phone-records", "cf-cctv-frame", "cf-transcript"]),
  ...pick(L_LibScience, ["sc-water-cycle", "sc-aquifer-drop", "sc-pipe-flow", "sc-molecule-orbit", "sc-cause-chain", "sc-reservoir-levels", "sc-warming-stripes", "sc-rain-gauges", "sc-dam-level", "sc-heat-sun"]),
};
